image: node:6.4.0

spellcheck:
  script:
    - npm install -g markdown-spellcheck
    - mdspell "**/*.md" --report --ignore-numbers

gitbook:
  script:
    - npm install -g gitbook-cli
    - gitbook install
    - gitbook build
