image: node:6.4.0

gitbook:
  stage: build
  script:
    - npm install -g gitbook-cli
    - gitbook install
    - gitbook build
  artifacts:
    paths:
    - _book

spellcheck:
  stage: test
  script:
    - npm install -g markdown-spellcheck
    - mdspell "content/**/*.md" "*.md" --ignore-numbers --report

pages:
  stage: deploy
  script:
    - cp -r _book public
  artifacts:
    paths:
    - public
  only:
    - master